alpha = { 'a'..'z' | 'A'..'Z' }
digit = { '0'..'9' }

start = _{ SOI ~ declaration* ~ EOI}

declaration = {
    architecture_declaration
}

collaboration_declaration = {
    "collaboration"
}

architecture_declaration = {
    "architecture"
}

component_declaration = {
    "component"
}

// csv file
field = { (ASCII_DIGIT | "." | "-")+ }
record = { field ~ ("," ~ field)* }
file = { SOI ~ (record ~ ("\r\n" | "\n"))* ~ EOI }